theme: jekyll-theme-hacker
description: "This GitHub project provides code, training, and teaching materials for Advance Placement Computer Science Principles High School students."
email: "nighthawkcodingsociety@gmail.com"